spring:
  application:
    name: BALANCE-SERVICE

  datasource:
    url: ${BALANCE_SERVICE_DB_URL:jdbc:postgresql://localhost:5434/balance_db}
    username: ${BALANCE_SERVICE_DB_USERNAME:postgres}
    password: ${BALANCE_SERVICE_DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    topic:
      orchestrator: orchestrator
      balance-check-success: balance-check-success
      balance-check-fail: balance-check-fail

    consumer:
      group-id: balance-group
      auto-offset-reset: latest

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_DEFAULT_ZONE_URL:http://localhost:8761/eureka/}

server:
  port: 8888