spring:
  application:
    name: BALANCE-SERVICE

  datasource:
    url: ${BALANCE_SERVICE_DB_URL:jdbc:postgresql://localhost:5434}
    username: ${BALANCE_SERVICE_DB_USERNAME:postgres}
    password: ${BALANCE_SERVICE_DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_DEFAULT_ZONE_URL:http://localhost:8761/eureka/}

server:
  port: 8888