spring:
  application:
    name: TRANSACTION-SERVICE

  data:
    mongodb:
      database: transaction-db
      uri: ${MONGO_URI:mongodb://transaction-db:admin@localhost:27020}


eureka:
  client:
    service-url:
      default-zone: ${EUREKA_DEFAULT_ZONE_URL:http://localhost:8761/eureka/}

server:
  port: 8091