services:
  user-db:
    container_name: user_db
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      TZ: "America/Sao_Paulo"
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: "user_db"