spring:
  application:
    name: USER-SERVICE

  datasource:
    url: jdbc:${DB_TYPE:postgresql}://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:user_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: transaction-group
      auto-offset-reset: latest

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_DEFAULT_ZONE_URL:http://localhost:8761/eureka/}

jwt:
  secret: ${JWT_SECRET:jwt-secret-example-here-fallback-string-to-avoid-exception}
  expiration-time: ${JWT_EXPIRATION:86400000}

server:
  port: 8090