spring:
  application:
    name: USER-SERVICE

  datasource:
    url: jdbc:${DB_TYPE:postgresql}://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:user_db}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    serviceUrl:
      default-zone : ${EUREKA_DEFAULT_ZONE_URL:http://localhost:8761/eureka/}

server:
  port: 8090