server:
  port: 8092

spring:
  application:
    name: FRAUD-SERVICE

  data:
    mongodb:
      database: fraud-db
      uri: ${MONGO_URI:mongodb://admin:admin@localhost:27018}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    topic:
      orchestrator: orchestrator
      fraud-check-success: fraud-check-success
      fraud-check-fail: fraud-check-fail
    consumer:
      group-id: fraud-group
      auto-offset-reset: latest

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_DEFAULT_ZONE_URL:http://localhost:8761/eureka/}